#!/usr/bin/env bash
echo "Starting script..."

echo "Updating Repositories"
sleep 2
apt-get update
wait
apt-get upgrade -y
wait

lite=0

while [ $# -gt 0 ]; do
  case "${1}" in
   -l|--lite)
      lite=1
      shift;;
    *)
  esac
done
    
if [ "${lite}" -eq 0 ]; then
  echo "Install all packages"
  sleep 2
  apt-get install -y gnome gnome-shell rpi-chromium-mods xorg #installs all required packges
  wait
else
echo "Install minimal options."
  sudo apt install -y gnome-session gnome-shell nautilus gedit gnome-terminal seahorse gnome-tweaks rpi-chromium-mods
  wait
fi

echo "Disabling dhcpcd to be able to connect to wifi via gnome network manager"
sleep 2
systemctl disable dhcpcd && /etc/init.d/dhcpcd stop
wait

echo "Correcting Audio for GNOME"
sleep 2
sudo sed -i 's/load-module module-udev-detect/load-module module-udev-detect tsched=0/g' /etc/pulse/default.pa
wait

#echo "Disable Animations"
#sleep 2
#sudo gsettings set org.gnome.desktop.interface enable-animations false
#wait

echo "change permission settings for GNOME"
sleep 2
sudo touch /etc/polkit-1/localauthority.conf.d/51-admin.conf
wait
sudo sh -c 'echo "[Configuration]" >> /etc/polkit-1/localauthority.conf.d/51-admin.conf'
wait
sudo sh -c 'echo "AdminIdentities=unix-group:sudo;unix-group:admin" >> /etc/polkit-1/localauthority.conf.d/51-admin.conf'
wait

echo "Rebooting, enjoy your new desktop!"
sleep 2
reboot
